/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apartment;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author AVINASH
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    Connection con=null;
    OraclePreparedStatement pst=null;
    OracleResultSet rs=null;
    OracleResultSet rsft=null;
    OracleResultSet rsfacil=null;
    OracleResultSet rsdept=null;
    OracleResultSet rsvis=null;
    OracleResultSet rsmnt=null;
    OracleResultSet rswo=null;
    public UI() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        MPanel = new javax.swing.JPanel();
        Welcome_pnl = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        Resident_pnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Res_Table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Flat_pnl = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Flat_Table = new javax.swing.JTable();
        Facilities_pnl = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Facility_Table = new javax.swing.JTable();
        Maintenance_pnl = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Mnt_Table = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Department_pnl = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dept_Table = new javax.swing.JTable();
        Visitors_pnl = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Visitors_Table = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Works_pnl = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        Works_Table = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Welcome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Resident = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Flat = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Facilities = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Maintenance = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Department = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Visitors = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Works_in = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));

        MPanel.setBackground(new java.awt.Color(250, 250, 250));
        MPanel.setPreferredSize(new java.awt.Dimension(640, 550));
        MPanel.setLayout(new java.awt.CardLayout());

        Welcome_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Welcome_pnl.setPreferredSize(new java.awt.Dimension(640, 550));
        Welcome_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(233, 99, 99));
        jLabel17.setText("Apartment Management System");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 8;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 164, 0, 0);
        Welcome_pnl.add(jLabel17, gridBagConstraints);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextPane1.setText("As the number of apartments are increasing day by day and even the number of residents in an apartment is increasing so it becomes tough to store the data of residents along with the staff details in the apartment manually. By having a database, the data gets consistently organized and remains easily accessible. The Apartment Management System provides users and programmers with a conservative and efficient means to create and manage the records instead of searching the records manually we can easily find the details of any resident. ");
        jTextPane1.setToolTipText("");
        jScrollPane8.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 388;
        gridBagConstraints.ipady = 134;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(221, 104, 126, 121);
        Welcome_pnl.add(jScrollPane8, gridBagConstraints);

        MPanel.add(Welcome_pnl, "card3");

        Resident_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Resident_pnl.setLayout(new java.awt.GridBagLayout());

        Res_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Rid", "RName", "Gender", "DOB", "Phone", "Flat No"
            }
        ));
        jScrollPane1.setViewportView(Res_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 537;
        gridBagConstraints.ipady = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(16, 39, 127, 37);
        Resident_pnl.add(jScrollPane1, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(233, 99, 99));
        jLabel5.setText("Resident");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Resident_pnl.add(jLabel5, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 61;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 39, 0, 0);
        Resident_pnl.add(jButton1, gridBagConstraints);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 68;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 18, 0, 0);
        Resident_pnl.add(jButton2, gridBagConstraints);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 71;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 18, 0, 0);
        Resident_pnl.add(jButton3, gridBagConstraints);

        jButton4.setText("Facilities");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(34, 18, 0, 37);
        Resident_pnl.add(jButton4, gridBagConstraints);

        MPanel.add(Resident_pnl, "card2");

        Flat_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Flat_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel9.setBackground(new java.awt.Color(233, 99, 99));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(233, 99, 99));
        jLabel9.setText("Flat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 94;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Flat_pnl.add(jLabel9, gridBagConstraints);

        Flat_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "FlatNo", "Flat Type"
            }
        ));
        jScrollPane2.setViewportView(Flat_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 256;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(88, 79, 138, 109);
        Flat_pnl.add(jScrollPane2, gridBagConstraints);

        MPanel.add(Flat_pnl, "card3");

        Facilities_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Facilities_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(233, 99, 99));
        jLabel12.setText("Facilities");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Facilities_pnl.add(jLabel12, gridBagConstraints);

        Facility_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Facility ID", "Facility Name"
            }
        ));
        jScrollPane3.setViewportView(Facility_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 400;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 48, 65);
        Facilities_pnl.add(jScrollPane3, gridBagConstraints);

        MPanel.add(Facilities_pnl, "card3");

        Maintenance_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Maintenance_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(233, 99, 99));
        jLabel14.setText("Maintenance");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Maintenance_pnl.add(jLabel14, gridBagConstraints);

        Mnt_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MID", "Name", "DID", "Salary"
            }
        ));
        jScrollPane5.setViewportView(Mnt_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 642;
        gridBagConstraints.ipady = 380;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(44, 83, 65, 99);
        Maintenance_pnl.add(jScrollPane5, gridBagConstraints);

        jButton5.setText("ADD Staff");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 65, 0, 0);
        Maintenance_pnl.add(jButton5, gridBagConstraints);

        jButton6.setText("Update");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 53, 0, 0);
        Maintenance_pnl.add(jButton6, gridBagConstraints);

        jButton7.setText("Delete");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 59, 0, 0);
        Maintenance_pnl.add(jButton7, gridBagConstraints);

        jButton8.setText("Update Salary");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(70, 45, 0, 0);
        Maintenance_pnl.add(jButton8, gridBagConstraints);

        MPanel.add(Maintenance_pnl, "card3");

        Department_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Department_pnl.setPreferredSize(new java.awt.Dimension(640, 530));
        Department_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(233, 99, 99));
        jLabel13.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Department_pnl.add(jLabel13, gridBagConstraints);

        dept_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Department ID", "Department Name"
            }
        ));
        jScrollPane4.setViewportView(dept_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 425;
        gridBagConstraints.ipady = 316;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(46, 72, 120, 116);
        Department_pnl.add(jScrollPane4, gridBagConstraints);

        MPanel.add(Department_pnl, "card3");

        Visitors_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Visitors_pnl.setPreferredSize(new java.awt.Dimension(640, 530));
        Visitors_pnl.setLayout(new java.awt.GridBagLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(233, 99, 99));
        jLabel15.setText("Visitors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 13;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 12, 0, 0);
        Visitors_pnl.add(jLabel15, gridBagConstraints);

        Visitors_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Phone", "Date", "Check_In", "Check_out", "Flat No"
            }
        ));
        jScrollPane6.setViewportView(Visitors_Table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 589;
        gridBagConstraints.ipady = 355;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(39, 12, 13, 12);
        Visitors_pnl.add(jScrollPane6, gridBagConstraints);

        jButton9.setText("Check In");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 44, 0, 0);
        Visitors_pnl.add(jButton9, gridBagConstraints);

        jButton10.setText("Check Out");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(57, 184, 0, 0);
        Visitors_pnl.add(jButton10, gridBagConstraints);

        MPanel.add(Visitors_pnl, "card3");

        Works_pnl.setBackground(new java.awt.Color(250, 250, 250));
        Works_pnl.setPreferredSize(new java.awt.Dimension(640, 550));
        Works_pnl.setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(233, 99, 99));
        jLabel16.setText("Works In");

        Works_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mid", "FlatNo"
            }
        ));
        jScrollPane7.setViewportView(Works_Table);

        jButton11.setText("Insert");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButton11)
                                .addGap(274, 274, 274))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 86;
        gridBagConstraints.ipady = 19;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        Works_pnl.add(jPanel3, gridBagConstraints);

        MPanel.add(Works_pnl, "card3");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Welcome.setBackground(new java.awt.Color(255, 255, 255));
        Welcome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                WelcomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                WelcomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                WelcomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                WelcomeMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 99, 99));
        jLabel1.setText("Welcome");

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(110, 0, 0, 0);
        jPanel2.add(Welcome, gridBagConstraints);

        Resident.setBackground(new java.awt.Color(255, 255, 255));
        Resident.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ResidentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ResidentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResidentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                ResidentMouseReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(233, 99, 99));
        jLabel2.setText("Resident");

        javax.swing.GroupLayout ResidentLayout = new javax.swing.GroupLayout(Resident);
        Resident.setLayout(ResidentLayout);
        ResidentLayout.setHorizontalGroup(
            ResidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResidentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ResidentLayout.setVerticalGroup(
            ResidentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResidentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Resident, gridBagConstraints);

        Flat.setBackground(new java.awt.Color(255, 255, 255));
        Flat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FlatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FlatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FlatMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FlatMouseReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(233, 99, 99));
        jLabel3.setText("Flat");

        javax.swing.GroupLayout FlatLayout = new javax.swing.GroupLayout(Flat);
        Flat.setLayout(FlatLayout);
        FlatLayout.setHorizontalGroup(
            FlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FlatLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FlatLayout.setVerticalGroup(
            FlatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FlatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Flat, gridBagConstraints);

        Facilities.setBackground(new java.awt.Color(255, 255, 255));
        Facilities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FacilitiesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FacilitiesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FacilitiesMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                FacilitiesMouseReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(233, 99, 99));
        jLabel4.setText("Facilities");

        javax.swing.GroupLayout FacilitiesLayout = new javax.swing.GroupLayout(Facilities);
        Facilities.setLayout(FacilitiesLayout);
        FacilitiesLayout.setHorizontalGroup(
            FacilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FacilitiesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        FacilitiesLayout.setVerticalGroup(
            FacilitiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FacilitiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Facilities, gridBagConstraints);

        Maintenance.setBackground(new java.awt.Color(255, 255, 255));
        Maintenance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaintenanceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaintenanceMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MaintenanceMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                MaintenanceMouseReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(233, 99, 99));
        jLabel6.setText("Maintenance");

        javax.swing.GroupLayout MaintenanceLayout = new javax.swing.GroupLayout(Maintenance);
        Maintenance.setLayout(MaintenanceLayout);
        MaintenanceLayout.setHorizontalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MaintenanceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        MaintenanceLayout.setVerticalGroup(
            MaintenanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaintenanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Maintenance, gridBagConstraints);

        Department.setBackground(new java.awt.Color(255, 255, 255));
        Department.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DepartmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DepartmentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DepartmentMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DepartmentMouseReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(233, 99, 99));
        jLabel7.setText("Department");

        javax.swing.GroupLayout DepartmentLayout = new javax.swing.GroupLayout(Department);
        Department.setLayout(DepartmentLayout);
        DepartmentLayout.setHorizontalGroup(
            DepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepartmentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        DepartmentLayout.setVerticalGroup(
            DepartmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DepartmentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Department, gridBagConstraints);

        Visitors.setBackground(new java.awt.Color(255, 255, 255));
        Visitors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VisitorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VisitorsMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VisitorsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                VisitorsMouseReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(233, 99, 99));
        jLabel8.setText("Visitors");

        javax.swing.GroupLayout VisitorsLayout = new javax.swing.GroupLayout(Visitors);
        Visitors.setLayout(VisitorsLayout);
        VisitorsLayout.setHorizontalGroup(
            VisitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VisitorsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        VisitorsLayout.setVerticalGroup(
            VisitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VisitorsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Visitors, gridBagConstraints);

        Works_in.setBackground(new java.awt.Color(255, 255, 255));
        Works_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Works_inMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Works_inMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Works_inMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Works_inMouseReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(233, 99, 99));
        jLabel10.setText("Works_In");

        javax.swing.GroupLayout Works_inLayout = new javax.swing.GroupLayout(Works_in);
        Works_in.setLayout(Works_inLayout);
        Works_inLayout.setHorizontalGroup(
            Works_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Works_inLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Works_inLayout.setVerticalGroup(
            Works_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Works_inLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Works_in, gridBagConstraints);

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogoutMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(233, 99, 99));
        jLabel11.setText("Logout");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 23;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel2.add(Logout, gridBagConstraints);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 560, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void updateTable(){
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","SYSTEM","mathias");
            String sql="select * from resident order by rid";
            PreparedStatement pst=con.prepareStatement(sql);
            rs = (OracleResultSet) pst.executeQuery();
            int i=0;
            Res_Table.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            i=0;
            String Flat="Select * from Flat order by flatno";
            PreparedStatement pst1=con.prepareStatement(Flat);
            rsft=(OracleResultSet) pst1.executeQuery();
            Flat_Table.setModel(DbUtils.resultSetToTableModel(rsft));
            
            
            i=0;
            String Facil="Select * from facilities order by FACILITY_ID";
            PreparedStatement pst2=con.prepareStatement(Facil);
            rsfacil=(OracleResultSet) pst2.executeQuery();
            Facility_Table.setModel(DbUtils.resultSetToTableModel(rsfacil));
            
            i=0;
            String dept="Select * from department order by did";
            PreparedStatement pst3=con.prepareStatement(dept);
            rsdept=(OracleResultSet) pst3.executeQuery();
            dept_Table.setModel(DbUtils.resultSetToTableModel(rsdept));
            
            i=0;
            String vis="Select * from Visitors order by dat, check_in";
            PreparedStatement pst4=con.prepareStatement(vis);
            rsvis=(OracleResultSet) pst4.executeQuery();
            while(rsvis.next()){
                Visitors_Table.getModel().setValueAt(rsvis.getString("Name"), i, 0);
                Visitors_Table.getModel().setValueAt(rsvis.getLong("Phone_No"), i, 1);
                Visitors_Table.getModel().setValueAt(rsvis.getDate("dat"), i, 2);
                Visitors_Table.getModel().setValueAt(rsvis.getString("Check_in"), i, 3);
                Visitors_Table.getModel().setValueAt(rsvis.getString("Check_out"), i, 4);
                Visitors_Table.getModel().setValueAt(rsvis.getInt("FlatNo"), i, 5);
                i++;
                
            }
            
            
            i=0;
            String Maintnc="Select * from Maintenance order by mid";
            PreparedStatement pst5=con.prepareStatement(Maintnc);
            rsmnt=(OracleResultSet) pst5.executeQuery();
            Mnt_Table.setModel(DbUtils.resultSetToTableModel(rsmnt));
            
            
            i=0;
            String work="Select * from WORKS_IN order by mid";
            PreparedStatement pst6=con.prepareStatement(work);
            rswo=(OracleResultSet) pst6.executeQuery();
            
                Works_Table.setModel(DbUtils.resultSetToTableModel(rswo));
                
                
            
            
        }
        catch(Exception e){

        }
        
    }
    private void WelcomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseEntered
        // TODO add your handling code here:
        setColor(Welcome);
    }//GEN-LAST:event_WelcomeMouseEntered

    private void WelcomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseExited
        // TODO add your handling code here:
        resetColor(Welcome);
    }//GEN-LAST:event_WelcomeMouseExited

    private void ResidentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidentMouseEntered
        // TODO add your handling code here:
        setColor(Resident);
    }//GEN-LAST:event_ResidentMouseEntered

    private void ResidentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidentMouseExited
        // TODO add your handling code here:
        resetColor(Resident);
    }//GEN-LAST:event_ResidentMouseExited

    private void FlatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlatMouseEntered
        // TODO add your handling code here:
        setColor(Flat);
    }//GEN-LAST:event_FlatMouseEntered

    private void FlatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlatMouseExited
        // TODO add your handling code here:
        resetColor(Flat);
    }//GEN-LAST:event_FlatMouseExited

    private void FacilitiesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacilitiesMouseEntered
        // TODO add your handling code here:
        setColor(Facilities);
    }//GEN-LAST:event_FacilitiesMouseEntered

    private void FacilitiesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacilitiesMouseExited
        // TODO add your handling code here:
        resetColor(Facilities);
    }//GEN-LAST:event_FacilitiesMouseExited

    private void WelcomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMousePressed
        // TODO add your handling code here:
        setColor1(Welcome);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Welcome_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_WelcomeMousePressed

    private void ResidentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidentMousePressed
        // TODO add your handling code here:
        setColor1(Resident);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Resident_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_ResidentMousePressed

    private void FlatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlatMousePressed
        // TODO add your handling code here:
        setColor1(Flat);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Flat_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
        
    }//GEN-LAST:event_FlatMousePressed

    private void FacilitiesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacilitiesMousePressed
        // TODO add your handling code here:
        setColor1(Facilities);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Facilities_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_FacilitiesMousePressed

    private void WelcomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_WelcomeMouseReleased
        // TODO add your handling code here:
        setColor(Welcome);
    }//GEN-LAST:event_WelcomeMouseReleased

    private void ResidentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResidentMouseReleased
        // TODO add your handling code here:
        setColor(Resident);
    }//GEN-LAST:event_ResidentMouseReleased

    private void FlatMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlatMouseReleased
        // TODO add your handling code here:
        setColor(Flat);
    }//GEN-LAST:event_FlatMouseReleased

    private void FacilitiesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacilitiesMouseReleased
        // TODO add your handling code here:
        setColor(Facilities);
    }//GEN-LAST:event_FacilitiesMouseReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Update_res up=new Update_res();
        up.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        add_aft a=new add_aft();
        a.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Del_aft del=new Del_aft();
        del.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MaintenanceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseEntered
        // TODO add your handling code here:
        setColor(Maintenance);
    }//GEN-LAST:event_MaintenanceMouseEntered

    private void MaintenanceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseExited
        // TODO add your handling code here:
        resetColor(Maintenance);
    }//GEN-LAST:event_MaintenanceMouseExited

    private void MaintenanceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMousePressed
        // TODO add your handling code here:
        setColor1(Maintenance);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Maintenance_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_MaintenanceMousePressed

    private void MaintenanceMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaintenanceMouseReleased
        // TODO add your handling code here:
        setColor(Maintenance);
    }//GEN-LAST:event_MaintenanceMouseReleased

    private void DepartmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseEntered
        // TODO add your handling code here:
        setColor(Department);
    }//GEN-LAST:event_DepartmentMouseEntered

    private void DepartmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseExited
        // TODO add your handling code here:
        resetColor(Department);
    }//GEN-LAST:event_DepartmentMouseExited

    private void DepartmentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMousePressed
        // TODO add your handling code here:
        setColor1(Department);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Department_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_DepartmentMousePressed

    private void DepartmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DepartmentMouseReleased
        // TODO add your handling code here:
        setColor(Department);
    }//GEN-LAST:event_DepartmentMouseReleased

    private void VisitorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorsMouseEntered
        // TODO add your handling code here:
        setColor(Visitors);
    }//GEN-LAST:event_VisitorsMouseEntered

    private void VisitorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorsMouseExited
        // TODO add your handling code here:
        resetColor(Visitors);
    }//GEN-LAST:event_VisitorsMouseExited

    private void VisitorsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorsMousePressed
        // TODO add your handling code here:
        setColor1(Visitors);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Visitors_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_VisitorsMousePressed

    private void VisitorsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VisitorsMouseReleased
        // TODO add your handling code here:
        setColor(Visitors);
    }//GEN-LAST:event_VisitorsMouseReleased

    private void Works_inMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Works_inMouseEntered
        // TODO add your handling code here:
        setColor(Works_in);
    }//GEN-LAST:event_Works_inMouseEntered

    private void Works_inMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Works_inMouseExited
        // TODO add your handling code here:
        resetColor(Works_in);
    }//GEN-LAST:event_Works_inMouseExited

    private void Works_inMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Works_inMousePressed
        // TODO add your handling code here:
        setColor1(Works_in);
        MPanel.removeAll();
        MPanel.revalidate();
        MPanel.repaint();
        
        MPanel.add(Works_pnl);
        MPanel.repaint();
        MPanel.revalidate();
        updateTable();
    }//GEN-LAST:event_Works_inMousePressed

    private void Works_inMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Works_inMouseReleased
        // TODO add your handling code here:
        setColor(Works_in);
    }//GEN-LAST:event_Works_inMouseReleased

    private void LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseEntered
        // TODO add your handling code here:
        setColor(Logout);
    }//GEN-LAST:event_LogoutMouseEntered

    private void LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseExited
        // TODO add your handling code here:
        resetColor(Logout);
    }//GEN-LAST:event_LogoutMouseExited

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        // TODO add your handling code here:
        setColor1(Logout);
       login l=new login();
       l.setVisible(true);
       this.dispose();
       updateTable();
    }//GEN-LAST:event_LogoutMousePressed

    private void LogoutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseReleased
        // TODO add your handling code here:
        setColor(Logout);
       
    }//GEN-LAST:event_LogoutMouseReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Facil_res fr=new Facil_res();
        fr.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Add_Staff a=new Add_Staff();
        a.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Del_Staff s=new Del_Staff();
        s.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Update_Staff u=new Update_Staff();
        u.setVisible(true);
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Update_Sal usal=new Update_Sal();
        usal.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Check_in c=new Check_in();
        c.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Ins_works iw=new Ins_works();
        iw.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        check_out c=new check_out();
        c.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
    void setColor(JPanel panel){
        panel.setBackground(new Color(255,153,153));
    }
    void resetColor(JPanel panel)
    {
        panel.setBackground(new Color(255, 255, 255));
    }
    void setColor1(JPanel panel){
        panel.setBackground(new Color(255,102, 102));
    }
    
    
              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Department;
    private javax.swing.JPanel Department_pnl;
    private javax.swing.JPanel Facilities;
    private javax.swing.JPanel Facilities_pnl;
    private javax.swing.JTable Facility_Table;
    private javax.swing.JPanel Flat;
    private javax.swing.JTable Flat_Table;
    private javax.swing.JPanel Flat_pnl;
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel MPanel;
    private javax.swing.JPanel Maintenance;
    private javax.swing.JPanel Maintenance_pnl;
    private javax.swing.JTable Mnt_Table;
    private javax.swing.JTable Res_Table;
    private javax.swing.JPanel Resident;
    private javax.swing.JPanel Resident_pnl;
    private javax.swing.JPanel Visitors;
    private javax.swing.JTable Visitors_Table;
    private javax.swing.JPanel Visitors_pnl;
    private javax.swing.JPanel Welcome;
    private javax.swing.JPanel Welcome_pnl;
    private javax.swing.JTable Works_Table;
    private javax.swing.JPanel Works_in;
    private javax.swing.JPanel Works_pnl;
    private javax.swing.JTable dept_Table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
